---
- name: Install build tools
  apt:
    name={{ item }}
    state=latest
  with_items:
    - build-essential
    - python3
    - python3-pip
    - freeglut3-dev

- name: Install python dependencies
  pip:
    name:
      - cpplint
    executable: pip3
